import type {
  User,
  Customer,
  Job,
  JobTask,
  Quote,
  TimeEntry,
  CallLog,
  CatalogItem,
  CompanySettings,
} from "./types";

export const COMPANY_NAME = "Ironclad Contracting";

export const defaultSettings: CompanySettings = {
  companyName: COMPANY_NAME,
  address: "900 Industrial Pkwy, Riverton",
  supportEmail: "office@ironcladcontracting.com",
  defaultLaborRate: 85,
  defaultMarkupPercent: 20,
  defaultTaxPercent: 8.25,
  businessType: "General contracting - remodeling, electrical, and repair",
  aiGreeting:
    "Thanks for calling Ironclad Contracting, this is the office assistant. How can I help?",
  aiHandoffRule: "urgent_only",
  openRouterModel: "meta-llama/llama-3.3-70b-instruct:free",
};

export const catalog: CatalogItem[] = [
  {
    id: "cat-1",
    name: "Quartz countertop slab",
    category: "Materials",
    unit: "each",
    price: 3200,
    vendor: "Stone Depot",
    description: "Standard-grade quartz slab, fabricated and installed for a typical kitchen run.",
  },
  {
    id: "cat-2",
    name: "Pressure-treated decking boards",
    category: "Materials",
    unit: "each",
    price: 2100,
    vendor: "Riverton Lumber Supply",
    description: "5/4x6 PT decking, enough to cover a 300 sqft deck.",
  },
  {
    id: "cat-3",
    name: "Deck railing kit",
    category: "Materials",
    unit: "each",
    price: 180,
    vendor: "Riverton Lumber Supply",
    description: "8ft pressure-treated railing section with balusters.",
  },
  {
    id: "cat-4",
    name: "200A breaker panel + wiring",
    category: "Materials",
    unit: "each",
    price: 1450,
    vendor: "Riverton Electrical Wholesale",
    description: "Panel upgrade kit including breakers and feed wire for a commercial cooler circuit.",
  },
  {
    id: "cat-5",
    name: "Vinyl plank flooring",
    category: "Materials",
    unit: "package",
    price: 980,
    vendor: "Riverton Flooring Co.",
    description: "Enough luxury vinyl plank to cover one rental unit turnover.",
  },
  {
    id: "cat-6",
    name: "Framing lumber & fasteners",
    category: "Materials",
    unit: "package",
    price: 420,
    vendor: "Riverton Lumber Supply",
    description: "Dimensional lumber and structural fasteners for small repair jobs.",
  },
  {
    id: "cat-7",
    name: "Interior paint, 5 gal",
    category: "Materials",
    unit: "each",
    price: 145,
    vendor: "Riverton Paint & Supply",
    description: "Eggshell interior paint, covers roughly 2000 sqft in one coat.",
  },
  {
    id: "cat-8",
    name: "Drywall sheet, 4x8",
    category: "Materials",
    unit: "each",
    price: 16,
    vendor: "Riverton Lumber Supply",
    description: "1/2\" standard drywall sheet.",
  },
  {
    id: "cat-9",
    name: "Standard duplex outlet & cover",
    category: "Materials",
    unit: "each",
    price: 9,
    vendor: "Riverton Electrical Wholesale",
    description: "15A residential duplex outlet with cover plate.",
  },
  {
    id: "cat-10",
    name: "Bathroom exhaust fan",
    category: "Materials",
    unit: "each",
    price: 95,
    vendor: "Riverton Electrical Wholesale",
    description: "Standard 80 CFM bathroom exhaust fan unit.",
  },
  {
    id: "cat-11",
    name: "Dumpster rental, 20 yard",
    category: "Equipment",
    unit: "week",
    price: 425,
    vendor: "Riverton Waste Services",
    description: "20-yard construction dumpster, weekly rate including one haul-away.",
  },
  {
    id: "cat-12",
    name: "Building permit filing fee",
    category: "Licenses & Fees",
    unit: "each",
    price: 250,
    vendor: "City of Riverton",
    description: "Standard residential permit filing and inspection fee.",
  },
  {
    id: "cat-13",
    name: "On-site estimate / consultation",
    category: "Consulting",
    unit: "visit",
    price: 0,
    vendor: "",
    description: "Free in-home consultation and measurement visit, booked by the AI line.",
  },
];

export const users: User[] = [
  {
    id: "u-mike",
    name: "Mike Ironside",
    role: "owner",
    title: "Owner",
    phone: "(555) 010-2200",
    email: "mike@ironcladcontracting.com",
    color: "#2563eb",
  },
  {
    id: "u-dana",
    name: "Dana Reyes",
    role: "employee",
    title: "Lead Carpenter",
    phone: "(555) 010-2201",
    email: "dana@ironcladcontracting.com",
    color: "#059669",
  },
  {
    id: "u-chris",
    name: "Chris Boone",
    role: "employee",
    title: "Electrician",
    phone: "(555) 010-2202",
    email: "chris@ironcladcontracting.com",
    color: "#d97706",
  },
  {
    id: "u-sam",
    name: "Sam Patel",
    role: "employee",
    title: "Apprentice",
    phone: "(555) 010-2203",
    email: "sam@ironcladcontracting.com",
    color: "#7c3aed",
  },
];

export const customers: Customer[] = [
  {
    id: "c-1",
    name: "Laura Whitfield",
    address: "482 Maple St, Riverton",
    phone: "(555) 220-1188",
    email: "laura.whitfield@example.com",
  },
  {
    id: "c-2",
    name: "Grant Family",
    address: "19 Birchwood Ln, Riverton",
    phone: "(555) 220-4432",
    email: "grantfamily@example.com",
  },
  {
    id: "c-3",
    name: "Riverton Diner",
    address: "1200 Main St, Riverton",
    phone: "(555) 220-7765",
    email: "manager@rivertondiner.com",
  },
  {
    id: "c-4",
    name: "Patel Rentals LLC",
    address: "77 Commerce Dr, Riverton",
    phone: "(555) 220-9910",
    email: "office@patelrentals.com",
  },
  {
    id: "c-5",
    name: "Owen Marsh",
    address: "5 Quarry Rd, Riverton",
    phone: "(555) 220-3321",
    email: "owen.marsh@example.com",
  },
  {
    id: "c-6",
    name: "Marlowe Fisher",
    address: "241 Elm Ct, Riverton",
    phone: "(555) 220-6602",
    email: "marlowe.fisher@example.com",
  },
];

export const quotes: Quote[] = [
  {
    id: "q-1001",
    title: "Kitchen remodel - cabinets & counters",
    customerId: "c-1",
    status: "accepted",
    createdAt: "2026-08-20",
    jobId: "j-2001",
    lineItems: [
      { id: "li-1", name: "Cabinet installation", category: "Labor", unit: "hour", quantity: 24, materialCost: 0, laborHours: 1 },
      { id: "li-2", name: "Quartz countertop slab", category: "Materials", unit: "each", quantity: 1, materialCost: 3200, laborHours: 0, catalogId: "cat-1" },
      { id: "li-3", name: "Sink & fixture install", category: "Labor", unit: "hour", quantity: 4, materialCost: 0, laborHours: 1 },
    ],
  },
  {
    id: "q-1002",
    title: "Deck rebuild - 300 sqft",
    customerId: "c-2",
    status: "accepted",
    createdAt: "2026-08-25",
    jobId: "j-2002",
    lineItems: [
      { id: "li-4", name: "Framing & demo", category: "Labor", unit: "hour", quantity: 30, materialCost: 0, laborHours: 1 },
      { id: "li-5", name: "Pressure-treated decking boards", category: "Materials", unit: "each", quantity: 1, materialCost: 2100, laborHours: 0, catalogId: "cat-2" },
      { id: "li-6", name: "Deck railing kit", category: "Materials", unit: "each", quantity: 3, materialCost: 180, laborHours: 0, catalogId: "cat-3" },
    ],
  },
  {
    id: "q-1003",
    title: "Walk-in cooler electrical upgrade",
    customerId: "c-3",
    status: "sent",
    createdAt: "2026-09-02",
    lineItems: [
      { id: "li-7", name: "Panel upgrade", category: "Labor", unit: "hour", quantity: 10, materialCost: 0, laborHours: 1 },
      { id: "li-8", name: "200A breaker panel + wiring", category: "Materials", unit: "each", quantity: 1, materialCost: 1450, laborHours: 0, catalogId: "cat-4" },
    ],
  },
  {
    id: "q-1004",
    title: "Unit turnover - flooring & paint",
    customerId: "c-4",
    status: "draft",
    createdAt: "2026-09-06",
    lineItems: [
      { id: "li-9", name: "Vinyl plank flooring", category: "Materials", unit: "package", quantity: 1, materialCost: 980, laborHours: 0, catalogId: "cat-5" },
      { id: "li-10", name: "Paint labor", category: "Labor", unit: "hour", quantity: 12, materialCost: 0, laborHours: 1 },
    ],
  },
  {
    id: "q-1005",
    title: "Front porch repair",
    customerId: "c-5",
    status: "declined",
    createdAt: "2026-08-15",
    lineItems: [
      { id: "li-11", name: "Structural repair", category: "Labor", unit: "hour", quantity: 8, materialCost: 0, laborHours: 1 },
      { id: "li-12", name: "Framing lumber & fasteners", category: "Materials", unit: "package", quantity: 1, materialCost: 420, laborHours: 0, catalogId: "cat-6" },
    ],
  },
  {
    id: "q-1006",
    title: "Living room trim & paint",
    customerId: "c-6",
    status: "accepted",
    createdAt: "2026-09-01",
    jobId: "j-2006",
    lineItems: [
      { id: "li-13", name: "Baseboard replacement", category: "Labor", unit: "hour", quantity: 10, materialCost: 0, laborHours: 1 },
      { id: "li-14", name: "Framing lumber & fasteners", category: "Materials", unit: "package", quantity: 1, materialCost: 210, laborHours: 0, catalogId: "cat-6" },
      { id: "li-15", name: "Interior wall paint", category: "Labor", unit: "hour", quantity: 14, materialCost: 0, laborHours: 1 },
      { id: "li-16", name: "Interior paint, 5 gal", category: "Materials", unit: "each", quantity: 1, materialCost: 145, laborHours: 0, catalogId: "cat-7" },
    ],
  },
];

export const jobs: Job[] = [
  {
    id: "j-2001",
    title: "Kitchen remodel - cabinets & counters",
    customerId: "c-1",
    status: "in_progress",
    scheduledDate: "2026-09-08",
    assignedEmployeeIds: ["u-dana", "u-sam"],
    quoteId: "q-1001",
    notes: "Cabinets delivered 9/5. Countertop template scheduled for 9/10.",
  },
  {
    id: "j-2002",
    title: "Deck rebuild - 300 sqft",
    customerId: "c-2",
    status: "scheduled",
    scheduledDate: "2026-09-10",
    assignedEmployeeIds: ["u-dana"],
    quoteId: "q-1002",
    notes: "Confirm lumber delivery before crew arrives.",
  },
  {
    id: "j-2003",
    title: "Emergency outlet repair",
    customerId: "c-5",
    status: "completed",
    scheduledDate: "2026-09-03",
    assignedEmployeeIds: ["u-chris"],
    notes: "Replaced two outlets, tested circuit. Customer paid on site.",
  },
  {
    id: "j-2004",
    title: "Walk-in cooler electrical upgrade",
    customerId: "c-3",
    status: "quoted",
    scheduledDate: "2026-09-15",
    assignedEmployeeIds: [],
    quoteId: "q-1003",
    notes: "Waiting on customer approval of quote.",
  },
  {
    id: "j-2005",
    title: "Gutter cleaning",
    customerId: "c-5",
    status: "invoiced",
    scheduledDate: "2026-08-29",
    assignedEmployeeIds: ["u-sam"],
    notes: "Invoice sent 8/30, due 9/13.",
  },
  {
    id: "j-2006",
    title: "Living room trim & paint",
    customerId: "c-6",
    status: "in_progress",
    scheduledDate: "2026-09-08",
    assignedEmployeeIds: ["u-dana", "u-sam"],
    quoteId: "q-1006",
    notes: "Customer wants baseboards swapped to a taller profile before painting.",
  },
];

const today = "2026-09-08";

// The task checklist a quote's labor line items expand into once there's a
// job to execute — see src/lib/task-templates.ts. Material line items don't
// get tasks (they're cost, not steps); only labor items do.
export const jobTasks: JobTask[] = [
  // j-2001 Kitchen remodel — from "Cabinet installation" + "Sink & fixture install"
  { id: "task-c1", jobId: "j-2001", title: "Remove old cabinets", status: "completed", order: 0, assignedEmployeeId: "u-dana" },
  { id: "task-c2", jobId: "j-2001", title: "Install cabinet boxes", status: "completed", order: 1, assignedEmployeeId: "u-dana" },
  { id: "task-c3", jobId: "j-2001", title: "Install doors & hardware", status: "pending", order: 2, assignedEmployeeId: "u-dana" },
  { id: "task-c4", jobId: "j-2001", title: "Final adjustment & cleanup", status: "pending", order: 3, assignedEmployeeId: null },
  { id: "task-c5", jobId: "j-2001", title: "Sink & fixture install", status: "completed", order: 4, assignedEmployeeId: "u-sam" },

  // j-2006 Living room trim & paint — from "Baseboard replacement" + "Interior wall paint"
  { id: "task-t1", jobId: "j-2006", title: "Remove old trim", status: "completed", order: 0, assignedEmployeeId: "u-dana" },
  { id: "task-t2", jobId: "j-2006", title: "Fill nail holes & caulk gaps", status: "completed", order: 1, assignedEmployeeId: "u-dana" },
  { id: "task-t3", jobId: "j-2006", title: "Install new trim", status: "in_progress", order: 2, assignedEmployeeId: "u-dana" },
  { id: "task-t4", jobId: "j-2006", title: "Caulk & touch up", status: "pending", order: 3, assignedEmployeeId: "u-dana" },
  { id: "task-t5", jobId: "j-2006", title: "Paint/finish trim", status: "pending", order: 4, assignedEmployeeId: null },
  { id: "task-t6", jobId: "j-2006", title: "Prep & protect surfaces", status: "completed", order: 5, assignedEmployeeId: "u-sam" },
  { id: "task-t7", jobId: "j-2006", title: "Patch and sand", status: "in_progress", order: 6, assignedEmployeeId: "u-sam" },
  { id: "task-t8", jobId: "j-2006", title: "Prime", status: "pending", order: 7, assignedEmployeeId: "u-sam" },
  { id: "task-t9", jobId: "j-2006", title: "Paint - coat 1", status: "pending", order: 8, assignedEmployeeId: null },
  { id: "task-t10", jobId: "j-2006", title: "Paint - coat 2", status: "pending", order: 9, assignedEmployeeId: null },
  { id: "task-t11", jobId: "j-2006", title: "Clean up", status: "pending", order: 10, assignedEmployeeId: null },
];

export const timeEntries: TimeEntry[] = [
  {
    id: "t-1",
    employeeId: "u-dana",
    jobId: "j-2001",
    taskId: "task-c2",
    date: today,
    clockIn: `${today}T07:00:00`,
    clockOut: `${today}T07:50:00`,
  },
  {
    id: "t-2",
    employeeId: "u-sam",
    jobId: "j-2001",
    taskId: "task-c5",
    date: today,
    clockIn: `${today}T08:10:00`,
    clockOut: `${today}T09:00:00`,
  },
  {
    id: "t-3",
    employeeId: "u-chris",
    jobId: "j-2003",
    taskId: null,
    date: "2026-09-03",
    clockIn: "2026-09-03T09:00:00",
    clockOut: "2026-09-03T11:30:00",
  },
  {
    id: "t-4",
    employeeId: "u-dana",
    jobId: "j-2002",
    taskId: null,
    date: "2026-09-05",
    clockIn: "2026-09-05T07:45:00",
    clockOut: "2026-09-05T15:50:00",
  },
  {
    id: "t-5",
    employeeId: "u-sam",
    jobId: "j-2005",
    taskId: null,
    date: "2026-08-29",
    clockIn: "2026-08-29T08:00:00",
    clockOut: "2026-08-29T12:15:00",
  },
  {
    id: "t-6",
    employeeId: "u-dana",
    jobId: "j-2006",
    taskId: "task-t1",
    date: today,
    clockIn: `${today}T08:00:00`,
    clockOut: `${today}T08:40:00`,
  },
  {
    id: "t-7",
    employeeId: "u-dana",
    jobId: "j-2006",
    taskId: "task-t2",
    date: today,
    clockIn: `${today}T08:40:00`,
    clockOut: `${today}T09:15:00`,
  },
  {
    id: "t-8",
    employeeId: "u-dana",
    jobId: "j-2006",
    taskId: "task-t3",
    date: today,
    clockIn: `${today}T09:15:00`,
    clockOut: null,
  },
  {
    id: "t-9",
    employeeId: "u-sam",
    jobId: "j-2006",
    taskId: "task-t6",
    date: today,
    clockIn: `${today}T08:45:00`,
    clockOut: `${today}T09:20:00`,
  },
  {
    id: "t-10",
    employeeId: "u-sam",
    jobId: "j-2006",
    taskId: "task-t7",
    date: today,
    clockIn: `${today}T09:20:00`,
    clockOut: null,
  },
];

export const callLogs: CallLog[] = [
  {
    id: "call-1",
    customerName: "New caller - unsaved number",
    customerPhone: "(555) 902-6634",
    channel: "call",
    startedAt: "2026-09-08T09:14:00",
    durationSec: 184,
    outcome: "booked",
    summary:
      "Caller wants a quote for a bathroom fan replacement. Booked an on-site estimate for 9/12 at 2:00 PM.",
    transcript: [
      { from: "ai", text: "Thanks for calling Ironclad Contracting, this is the office assistant. How can I help?" },
      { from: "customer", text: "Hi, my bathroom fan stopped working and I think it needs replacing." },
      { from: "ai", text: "Happy to help. Can I get your name and address so we can schedule a free estimate?" },
      { from: "customer", text: "Sure, it's Ben Carrow, 14 Hollow Creek Rd." },
      { from: "ai", text: "Got it. We have an opening this Friday, 9/12, at 2:00 PM for a free estimate - does that work?" },
      { from: "customer", text: "Yes, that works." },
      { from: "ai", text: "You're booked for Friday 9/12 at 2:00 PM. You'll get a text confirmation shortly. Anything else?" },
      { from: "customer", text: "Nope, that's it, thanks." },
    ],
  },
  {
    id: "call-2",
    customerName: "Riverton Diner",
    customerPhone: "(555) 220-7765",
    channel: "text",
    startedAt: "2026-09-07T13:02:00",
    durationSec: 0,
    outcome: "message_taken",
    summary:
      "Following up on quote q-1003 for the walk-in cooler electrical upgrade. Wants to know if it can start next week.",
    transcript: [
      { from: "customer", text: "Hi, checking on the quote you sent for the cooler panel upgrade - can that start next week?" },
      { from: "ai", text: "Thanks for the follow up! Let me pass that along to the team and have them confirm scheduling with you shortly." },
    ],
  },
  {
    id: "call-3",
    customerName: "Unknown caller",
    customerPhone: "(555) 771-0098",
    channel: "call",
    startedAt: "2026-09-06T16:40:00",
    durationSec: 96,
    outcome: "escalated",
    summary:
      "Caller reports water actively leaking through a ceiling. Flagged as urgent and escalated to Mike directly.",
    transcript: [
      { from: "ai", text: "Thanks for calling Ironclad Contracting, how can I help?" },
      { from: "customer", text: "Water is coming through my ceiling right now, I need someone today!" },
      { from: "ai", text: "That sounds urgent - I'm connecting you to our on-call lead right now, please stay on the line." },
    ],
  },
  {
    id: "call-4",
    customerName: "Owen Marsh",
    customerPhone: "(555) 220-3321",
    channel: "call",
    startedAt: "2026-09-05T10:20:00",
    durationSec: 41,
    outcome: "missed",
    summary: "Call disconnected before the assistant could take details. No callback number captured.",
    transcript: [
      { from: "ai", text: "Thanks for calling Ironclad Contracting, this is the office assistant." },
    ],
  },
  {
    id: "call-5",
    customerName: "Grant Family",
    customerPhone: "(555) 220-4432",
    channel: "text",
    startedAt: "2026-09-04T18:11:00",
    durationSec: 0,
    outcome: "booked",
    summary: "Confirmed deck rebuild start date of 9/10 and asked to move a planter before crew arrives.",
    transcript: [
      { from: "customer", text: "Just confirming the deck crew is still good for the 10th?" },
      { from: "ai", text: "Yes, you're confirmed for Thursday 9/10. If you can move any planters or furniture off the deck beforehand that would help the crew get started quickly." },
      { from: "customer", text: "Will do, thanks!" },
    ],
  },
];
